package com.pavelwinter.greendmamytom;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pavelwinter.greendmamytom.JoinProductWithOrders;
import com.pavelwinter.greendmamytom.Order;
import com.pavelwinter.greendmamytom.Product;

import com.pavelwinter.greendmamytom.JoinProductWithOrdersDao;
import com.pavelwinter.greendmamytom.OrderDao;
import com.pavelwinter.greendmamytom.ProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig joinProductWithOrdersDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig productDaoConfig;

    private final JoinProductWithOrdersDao joinProductWithOrdersDao;
    private final OrderDao orderDao;
    private final ProductDao productDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        joinProductWithOrdersDaoConfig = daoConfigMap.get(JoinProductWithOrdersDao.class).clone();
        joinProductWithOrdersDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        joinProductWithOrdersDao = new JoinProductWithOrdersDao(joinProductWithOrdersDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);

        registerDao(JoinProductWithOrders.class, joinProductWithOrdersDao);
        registerDao(Order.class, orderDao);
        registerDao(Product.class, productDao);
    }
    
    public void clear() {
        joinProductWithOrdersDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
    }

    public JoinProductWithOrdersDao getJoinProductWithOrdersDao() {
        return joinProductWithOrdersDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

}
