package com.pavelwinter.greendmamytom;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOIN_PRODUCT_WITH_ORDERS".
*/
public class JoinProductWithOrdersDao extends AbstractDao<JoinProductWithOrders, Long> {

    public static final String TABLENAME = "JOIN_PRODUCT_WITH_ORDERS";

    /**
     * Properties of entity JoinProductWithOrders.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property ProductId = new Property(1, Long.class, "productId", false, "PRODUCT_ID");
        public final static Property OrderId = new Property(2, Long.class, "orderId", false, "ORDER_ID");
    };


    public JoinProductWithOrdersDao(DaoConfig config) {
        super(config);
    }
    
    public JoinProductWithOrdersDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOIN_PRODUCT_WITH_ORDERS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: _id
                "\"PRODUCT_ID\" INTEGER," + // 1: productId
                "\"ORDER_ID\" INTEGER);"); // 2: orderId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOIN_PRODUCT_WITH_ORDERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JoinProductWithOrders entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(2, productId);
        }
 
        Long orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindLong(3, orderId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JoinProductWithOrders entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(2, productId);
        }
 
        Long orderId = entity.getOrderId();
        if (orderId != null) {
            stmt.bindLong(3, orderId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JoinProductWithOrders readEntity(Cursor cursor, int offset) {
        JoinProductWithOrders entity = new JoinProductWithOrders( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // productId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // orderId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JoinProductWithOrders entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setOrderId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JoinProductWithOrders entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JoinProductWithOrders entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
